# Code 테이블에 Rent_STATUS 추가

INSERT INTO CODE(CODE_NAME, CODE_DEPTH, CODE_DETAIL)
VALUES('01', 'RENT_STATUS', '대여 요청 중');

INSERT INTO CODE(CODE_NAME, CODE_DEPTH, CODE_DETAIL)
VALUES('02', 'RENT_STATUS', '대여중');

INSERT INTO CODE(CODE_NAME, CODE_DEPTH, CODE_DETAIL)
VALUES('03', 'RENT_STATUS', '대여 완료');
